### ISSUE TITLE
Missing bot command buttons

### ISSUE THREAD

**Issue by Lerosen** [Raabi91/moonraker-telegram#102]
Hi,

I just set up a new instance with a new bot and the command buttons are not displayed for the bot. The commands themselves work just fine. I also get no command suggestions when typing.

**Comment by Raabi91** [comment]
Do you have Set up your Buttons für like Here? 

https://github.com/Raabi91/moonraker-telegram/blob/master/docs/FAQ.md#how-to-use-commands-with-buttons-in-telegram

**Comment by Lerosen** [comment]
Nope, must have overlooked it. Sorry
