### ISSUE TITLE
After print finished, keeps reporting idle state

### ISSUE THREAD

**Issue by TheLion** [Raabi91/moonraker-telegram#108]
Hi,

Since the latest update (v1.0.2-222-g4a2751c), the moonraker-telegram program/addon keeps reporting the idle state of the printer, in my case, every 15 min, after the print is done.

I ultimately rebooted the whole RPi and that stopped it. (Not sure yet if this fixed the issue completely, or only for this print.)

This wasn't happening before the latest update.

**Comment by Raabi91** [comment]
Hi
i have tried everything possible to reproduce this. unfortunately, everything is still running normally for me. has the error now occurred again

**Comment by TheLion** [comment]
I just finished a print and the issue didn't happen. Strange...
