### ISSUE TITLE
gif shows picture but state does not

### ISSUE THREAD

**Issue by Poikilos** [Raabi91/moonraker-telegram#114]
- Version: [8a751ea](https://github.com/Raabi91/moonraker-telegram/commit/8a751ea1e659971e6509de456f19289dd047d247)

## Expected behavior
`/state` should show a picture with the following conf (I was using the **defaults** for settings below;  only relevant part of conf shown):
```
picture="0"
#in this report you can turn off individual images for the individual status. to set no pic set it to "0"
pic_start="1"
pic_error="1"
pic_pause="1"
pic_end="1"
pic_state="1"
pic_standby="1"
pic_complete="1"
pic_paused="1"
pic_bed_cooldown="1"
```

## Actual behavior
`/gif` generates a gif animation, but `/state` does not show a picture.

Related (?):
- The documentation says the conf file is telegram_config.sh, but it is actually named telegram_config.conf (as generated during install).

**Comment by Poikilos** [comment]
`~/printer_data/logs/moonraker.log` shows no errors in moonraker-telegram, and the url in the conf is correct (tested by pasting into browser)

**Comment by Raabi91** [comment]
Sr,y for late replay you have set picture to 1 to enable images global.

**Comment by Poikilos** [comment]
Works. Thanks!
