### ISSUE TITLE
Round issue

### ISSUE THREAD

**Issue by mtmello2003** [Raabi91/moonraker-telegram#117]
I´ve got some Z value with round issue.

Look for the image:

![image](https://github.com/Raabi91/moonraker-telegram/assets/15361590/6eea1982-6e5e-4867-9b38-d4d633fe97a5)

**Comment by Raabi91** [comment]
i will check it

**Comment by mtmello2003** [comment]
I didn´t pay attention but look at the print screen I sent: also the bed and extruder temperature has rounding issue (1 digit instead 2).
