### ISSUE TITLE
Placeholders do not work

### ISSUE THREAD

**Issue by mtmello2003** [Raabi91/moonraker-telegram#118]
With my Elegoo neptune 4 plus, both placeholders:
| $layers          | Total Layers                                    |
| $current_layer   | Current Layer
Do not work:

![image](https://github.com/Raabi91/moonraker-telegram/assets/15361590/94dcf986-0eb0-4863-a4f0-cd6eb054db40)

msg_state="Printing $print_filename at $print_progress. Current Time $print_current. Remaining Time $print_remaining. Bed $bed_temp/$bed_target. E0 $extruder_temp/$extruder_target. Z $z_current. Layer: $current_layer / $layers."

**Comment by Raabi91** [comment]
it works here without problems. try to reinstall bc which we need for the layer calculation.

sudo apt-get install bc

**Comment by mtmello2003** [comment]
I did first sudo apt-get update
and after: 
```
mks@mkspi:~$ sudo apt-get install bc
Reading package lists... Done
Building dependency tree
Reading state information... Done
bc is already the newest version (1.07.1-2+b1).
0 upgraded, 0 newly installed, 0 to remove and 239 not upgraded.
```
Did nothing...
