### ISSUE TITLE
multi_config.sh is created with a new line at the beginning causing an error "/n"

### ISSUE THREAD

**Issue by tannerellen** [Raabi91/moonraker-telegram#15]
When installing there is a command not found error from multi_config.sh:

"/home/pi/moonraker-telegram/moonraker-telegram-1/multi_config.sh: line 1: n: command not found"

Removing the stray "\n" and running the install again no longer reports the error.

**Comment by Raabi91** [comment]
Thanks for the report i will fix it at the evening

**Comment by Raabi91** [comment]
fixed
