### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hevilp** [Raabi91/moonraker-telegram#3]
Hi,

nice work! Possible to create a gcode macro in klipper to send a message?. would like to use it after a certain command in my macros.

**Comment by Raabi91** [comment]
hey
i just put the whole thing in. to send messages (everything without an image at the moment) you have to install the shell plugin for clipper. you do this best with the kiauh script. after that you can use the config


```
[gcode_shell_command telegram]
command: sh /home/pi/moonraker-telegram/scripts/telegram.sh "this is a message from your printer"
timeout: 2.
verbose: false
[gcode_macro telegram]
gcode:
    RUN_SHELL_COMMAND CMD=telegram
```

send you messages. like in the normal config, swap the text between the "". if you need more, just copy and paste and create a new command
