### ISSUE TITLE
Moonraker log: Unauthorized, [No User]

### ISSUE THREAD

**Issue by DrCoolHands** [Raabi91/moonraker-telegram#61]
Hello,

I setup the moonraker-telegram bot on FluidOS Pi image and get the following errors in the Moonraker.log:

`2021-09-07 21:21:47,099 [web.py:log_exception()] - 401 GET /websocket (127.0.0.1): Unauthorized`
`2021-09-07 21:21:47,102 [app.py:log_request()] - 401 GET /websocket (127.0.0.1) [No User] 5.73ms`
`2021-09-07 21:21:57,123 [web.py:log_exception()] - 401 GET /websocket (127.0.0.1): Unauthorized`
`2021-09-07 21:21:57,126 [app.py:log_request()] - 401 GET /websocket (127.0.0.1) [No User] 6.50ms`
`2021-09-07 21:22:07,147 [web.py:log_exception()] - 401 GET /websocket (127.0.0.1): Unauthorized`
`2021-09-07 21:22:07,150 [app.py:log_request()] - 401 GET /websocket (127.0.0.1) [No User] 5.49ms`

I am using user authentication in Fluidd, not sure how that works back with Moonraker.

**Comment by Raabi91** [comment]
Moonraker telegram does not currently work with user authentication. But since I'm currently in exam stress, I unfortunately don't have time to integrate it at the moment.

**Comment by Raabi91** [comment]
with the last update the whole thing should now be possible via the api key as far as i could test it

**Comment by DrCoolHands** [comment]
I can confirm that the added API key works with force login = true.
Thank you!
