### ISSUE TITLE
Request: Notifications for bed temperature after print

### ISSUE THREAD

**Issue by Kaiede** [Raabi91/moonraker-telegram#62]
One thing I miss from OctoPod is that it could notify you when the bed reached a certain temperature after the print had completed. I used this to be notified after ASA/ABS/PETG prints to let me know when it had cooled down enough that I could remove the printed parts.

It looks like the heater temps are provided as part of the notify_status_update object, so it at least seems feasible?

**Comment by Raabi91** [comment]
thanks to @nknotts. he has integrated this and sent a pull request. therefore it is available now
