### ISSUE TITLE
[Question] led_on / led_off multiple

### ISSUE THREAD

**Issue by Jack77777777** [Raabi91/moonraker-telegram#68]
1. Can i setup more than one led to power on/off ?
2. Is there a command for a snapshot/picture, not gif ? If not i can configure it with own custom MSG.

**Comment by Raabi91** [comment]
1. if u use the monraker power plugin or gcode macro sure

2. an snapshot comand is atm not avaible it comes in the next update

**Comment by Jack77777777** [comment]
If i set up this way:
led_on="http://127.0.0.1:$port/machine/device_power/on?FRAME_LIGHT"
led_on="http://127.0.0.1:$port/printer/gcode/script?script=POWER_ON_CAMLIGHT"
only the second executes. When commenting out the second, the first executes.
How can i have both executed ?

**Comment by Raabi91** [comment]
with a custom gcode macro in klipper like this

[gcode_macro LEDS_ON_FOR_CAM]
gcode:
 POWER_ON_CAMLIGHT
 {action_call_remote_method("set_device_power",
                             device="FRAME_LIGHT"",
                             state="on")}
                             
then put this in the telegram config:
http://127.0.0.1:$port/printer/gcode/script?script=LEDS_ON_FOR_CAM"

**Comment by Jack77777777** [comment]
I am so dump. Closing this.
