### ISSUE TITLE
Telegram not getting answer

### ISSUE THREAD

**Issue by sharkyenergy** [Raabi91/moonraker-telegram#69]
Hello!

first off, thank you for your precious work. I installed it today and got it working, but after 1 hour it didnt work anymore. I did not change anything in the meantime. I send /state and get no answer.

this is the output:
```

text
xxxxxxxxxx
Got chat: xxxxxxxxxx
chat  id: xxxxxxxxx
Got command: /state
chat id are same
(standard_in) 1: syntax error
(standard_in) 2: syntax error


(standard_in) 1: syntax error
Handshake status 401 Unauthorized
### closed ###
Retry : Sat Dec 11 19:54:08 2021
Handshake status 401 Unauthorized
### closed ###
```

these are my trusted clients in moonracker config:

```

trusted_clients:
  10.0.0.0/8
  127.0.0.0/8
  169.254.0.0/16
  172.16.0.0/12
  192.168.0.0/16
  FE80::/10
  ::1/128
```

and I already added [respond] to my printer config.

Any Idea of what might be wrong? Already tried restarting, no luck.

thank you have a nice day

**Comment by Raabi91** [comment]
did you use fluidd or mainsail? if u use fluidd is force_logins True in moonraker??

**Comment by sharkyenergy** [comment]
I am using fluidd and yes, force logins is set to true because I need to login from remote.

**Comment by sharkyenergy** [comment]
I found the part about the api key in the telegram config. added the api key and now it works properly! thank you very much!
