### ISSUE TITLE
After Complete Installation, Fluidd Gives Error For Moonraker 'update_manager error'

### ISSUE THREAD

**Issue by Declan0811** [Raabi91/moonraker-telegram#75]
Basically the title, I have gone through the entire guide, but I am being hit by a ton of errors, and cannot figure out what to do. I have attached the log file, and any help would be greatly appreciated!
[moonraker (1).log](https://github.com/Raabi91/moonraker-telegram/files/7760088/moonraker.1.log)

**Comment by Raabi91** [comment]
The log say that the virtuell env is missing. Ich got you any error at Installation?

**Comment by Declan0811** [comment]
> The log say that the virtuell env is missing. Got you any error at Installation? 

No, I did not get any errors. Is there a way to reinstall everything, and try again?

**Comment by Declan0811** [comment]
Nevermind, I just had to sudo when using './scripts/install.sh'
