### ISSUE TITLE
make button at keyboard

### ISSUE THREAD

**Issue by tayanov** [Raabi91/moonraker-telegram#77]
Please make  button at keyboard like this repo
https://github.com/nlef/moonraker-telegram-bot

**Comment by Raabi91** [comment]
![Screenshot_20220109-133149_Telegram](https://user-images.githubusercontent.com/38133278/148682307-be18b167-55c2-41a2-b604-fee6b8611c08.jpg)
![Screenshot_20220109-133144_Telegram](https://user-images.githubusercontent.com/38133278/148682309-2ed005e9-b0dc-447c-9e64-146c92ce9f77.jpg)
Like this? This already Working
