### ISSUE TITLE
Request: Ability to switch photo per action

### ISSUE THREAD

**Issue by nuxy69** [Raabi91/moonraker-telegram#80]
Right now there is only an option to switch photo on/off. Which will add a photo to every action. 
The "Started printing" for example does not need a photo. As there shouldn't be anything on the build plate. 
It would be great to be able to have more control on which action will add photo or not.

**Comment by Raabi91** [comment]
so with the last update you can now additionally decide which message a picture should have

https://github.com/Raabi91/moonraker-telegram/blob/master/docs/Telegram_config.md#with-these-variables-you-can-disable-images-for-individual-messages-to-disable-set-to-0

**Comment by nuxy69** [comment]
Awesome! Thank you!
