### ISSUE TITLE
FR: Omit PAUSE notifications for moonraker-timelapse park moves

### ISSUE THREAD

**Issue by zellneralex** [Raabi91/moonraker-telegram#82]
Hi, 

we need to use PAUSE/RESUME for the park head feature in the moonraker-timelapse. To give the clients a change to distinguish if it is a timelapse park move the macro would provides a flag called printer[“gcode_macro TIMELAPSE_TAKE_FRAME“].is_paused.

You should omit the notifications if that and printer.pause_resume.is_paused are set to true.

**Comment by Raabi91** [comment]
is now integrated in the main branch and should work. 4 test prints ran with me without problems

**Comment by zellneralex** [comment]
Thank you
