### ISSUE TITLE
/photo Unknown Command

### ISSUE THREAD

**Issue by crimsonclyde** [Raabi91/moonraker-telegram#83]
Hi,

updated Telegram Bot with KIAUH to v1.4.1.-14

Now command /photo is not working any more.

KIAUH v3.1.0-95
Moonraker: v0.7.1.-376

Config Camera
```
[camera]
host: http://localhost:8080/?action=stream
```

systemctl
```
Feb 18 20:15:36 fluiddpi python[3512]: 2022-02-18 20:15:36,831 - camera - WARNING - Reading video frames queue exception <built-in method with_traceback of Empty object at 0xa40643e8>
Feb 18 20:15:36 fluiddpi python[3512]: 2022-02-18 20:15:36,763 - camera - WARNING - Reading video frames queue exception <built-in method with_traceback of Empty object at 0xa40643e8>
```

Telegram.log is empty. /video is working.
Did a fresh installation via KIAUH nothing.
Any advice?

**Comment by Raabi91** [comment]
this is the wrong plugin u use the telegram plugin form nlef
