### ISSUE TITLE
Plugin sends new and old screenshot

### ISSUE THREAD

**Issue by TheLion** [Raabi91/moonraker-telegram#89]
I just updated the plugin to v1.0.2-188-ge95e4d3 and it sends the correct screenshot, but also an old one, in my case the last one from a previous (not last) job. See screenshots from Telegram below.

![A826230D-F66F-4381-A8DE-0E1A4D834457](https://user-images.githubusercontent.com/3755011/156899929-b3a33870-5e0c-410b-995a-ad2448f646e8.png)
![B5115C68-674D-472D-A948-3479D0F78E9A](https://user-images.githubusercontent.com/3755011/156899931-393bdd33-2241-4340-a224-2b6f94286ee0.png)

Is there a cache/file I need to empty/delete?

**Comment by Raabi91** [comment]
have published another update since I'm back home. should now no longer happen

**Comment by TheLion** [comment]
Yes, I can confirm. Issue is solved with update.
